name: Build and Push Container

on:
  push:
    branches: [ main ]
    paths:
      - 'src/inference_stub/**'
      - '.github/workflows/build-and-push.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write   # allow pushing to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image name
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/inference-api:latest" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/inference_stub
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image
        run: echo "Pushed ${{ steps.vars.outputs.IMAGE }}"
